# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromcity', models.CharField(choices=[('1', 'Hubli'), ('2', 'Bangalore'), ('3', 'Mumbai')], default='empty', max_length=40)),
                ('to', models.CharField(choices=[('1', 'Hubli'), ('2', 'Bangalore'), ('3', 'Mumbai')], default='empty', max_length=40)),
                ('date_of_journey', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_journey', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
